name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    # Step 4: Build the documentation
    - name: Build Sphinx documentation
      run: |
        sphinx-build -b html docs/ docs/build/  # Adjust paths if necessary

    # Step 5: Deploy to GitHub Pages
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        src: ./docs/build  # Path to the generated HTML documentation
